### ISSUE TITLE
ActualVim stopped working

### ISSUE THREAD

**Issue by xelra** [lunixbochs/ActualVim#103]
Hi there. I haven't been very active these past few months and when I wanted to get started with ActualVim for my new Go project, it didn't work anymore.

After I upgraded to the latest commit in master, I'm getting this:

```
DPI scale: 1
startup, version: 3126 windows x64 channel: stable
executable: /C/Program Files/Sublime Text 3/sublime_text.exe
working dir: /C/Program Files/Sublime Text 3
packages path: /C/Users/xelra/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/xelra/AppData/Roaming/Sublime Text 3/Local
zip path: /C/Program Files/Sublime Text 3/Packages
zip path: /C/Users/xelra/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.11481
startup time: 0.14781
first paint time: 0.14881
first paint time: 0.14881
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin actualvim.actual
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\actual.py", line 6, in <module>
    from .view import ActualVim
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\view.py", line 7, in <module>
    from . import neo
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\neo.py", line 10, in <module>
    from .lib import neovim
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\lib\neovim\__init__.py", line 8, in <module>
    from .api import Nvim
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\lib\neovim\api\__init__.py", line 7, in <module>
    from .buffer import Buffer
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\lib\neovim\api\buffer.py", line 2, in <module>
    from .common import Remote
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\lib\neovim\api\common.py", line 4, in <module>
    from ActualVim.lib import msgpack
ImportError: No module named 'ActualVim'
reloading plugin actualvim.edit
reloading plugin actualvim.neo
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\neo.py", line 10, in <module>
    from .lib import neovim
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\lib\neovim\__init__.py", line 8, in <module>
    from .api import Nvim
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\lib\neovim\api\__init__.py", line 7, in <module>
    from .buffer import Buffer
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\lib\neovim\api\buffer.py", line 2, in <module>
    from .common import Remote
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\lib\neovim\api\common.py", line 4, in <module>
    from ActualVim.lib import msgpack
ImportError: No module named 'ActualVim'
reloading plugin actualvim.screen
reloading plugin actualvim.settings
reloading plugin actualvim.view
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\view.py", line 7, in <module>
    from . import neo
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\neo.py", line 10, in <module>
    from .lib import neovim
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\lib\neovim\__init__.py", line 8, in <module>
    from .api import Nvim
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\lib\neovim\api\__init__.py", line 7, in <module>
    from .buffer import Buffer
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\lib\neovim\api\buffer.py", line 2, in <module>
    from .common import Remote
  File "C:\Users\xelra\AppData\Roaming\Sublime Text 3\Packages\actualvim\lib\neovim\api\common.py", line 4, in <module>
    from ActualVim.lib import msgpack
ImportError: No module named 'ActualVim'
plugins loaded
Package Control: Skipping automatic upgrade, last run at 2017-05-18 01:00:59, next run at 2017-05-18 02:00:59 or after

```

**Comment by justinmk** [comment]
@xelra see https://github.com/lunixbochs/ActualVim/search?q=ImportError%3A+No+module+named+%27ActualVim%27&type=Issues&utf8=%E2%9C%93

I think it just needs a rename or reinstall.

**Comment by xelra** [comment]
Thanks. Renaming the project directory has solved it.
