### ISSUE TITLE
Error when plugin loading ( method 'vim_get_api_info' )

### ISSUE THREAD

**Issue by SrMordred** [lunixbochs/ActualVim#109]
Win 10 x64
neovim x64
sublime 3

Pasting from sublime console:
```
reloading plugin ActualVim.view
plugins loaded
ActualVim: using nvim binary path: F:\neovim\bin\nvim.exe
ActualVim: Error during nvim setup.
Traceback (most recent call last):
  File "F:\sublime\Data\Packages\ActualVim\neo.py", line 80, in plugin_loaded
    vim._setup()
  File "F:\sublime\Data\Packages\ActualVim\neo.py", line 130, in _setup
    self.nv.input('<FocusGained>')
  File "F:\sublime\Data\Packages\ActualVim\lib\neovim\api\nvim.py", line 285, in input
    return self.request('nvim_input', bytes)
  File "F:\sublime\Data\Packages\ActualVim\lib\neovim\api\nvim.py", line 134, in request
    res = self._session.request(name, *args, **kwargs)
  File "F:\sublime\Data\Packages\ActualVim\lib\neovim\msgpack_rpc\session.py", line 110, in request
    raise self.error_wrapper(err)
ActualVim.lib.neovim.api.nvim.NvimError: b'Invalid method name'
```
I put some prints on session.py to get some info and the method that they are trying to call is this:
`b'vim_get_api_info'`

**Comment by SrMordred** [comment]
nvm. 
The issue is with neovim Release (v0.2).
The Development (pre-release) works fine.
