### ISSUE TITLE
Error while loading nvim pipe_data_received

### ISSUE THREAD

**Issue by mjedmonds** [lunixbochs/ActualVim#110]
Trying to get actualvim setup but I'm running into this problem. It looks like it's crashing when it sees the normal Vim startup screen.

Any guidance is appreciated.

```
ActualVim: using nvim binary path: /usr/local/bin/nvim
DEBUG:ActualVim.lib.asyncio:Using selector: KqueueSelector
ERROR:ActualVim.lib.asyncio:Exception in callback AsyncioEventLoop.pipe_data_received(2, b'VIM - Vi IM...h: "vim -h"\n')
handle: <Handle AsyncioEventLoop.pipe_data_received(2, b'VIM - Vi IM...h: "vim -h"\n')>
Traceback (most recent call last):
  File "/Users/mark/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/Users/mark/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/event_loop/asyncio.py", line 59, in pipe_data_received
    self._on_stderr(data)
AttributeError: 'AsyncioEventLoop' object has no attribute '_on_stderr'
ActualVim: Error during nvim setup.
Traceback (most recent call last):
  File "/Users/mark/Library/Application Support/Sublime Text 3/Packages/ActualVim/neo.py", line 80, in plugin_loaded
    vim._setup()
  File "/Users/mark/Library/Application Support/Sublime Text 3/Packages/ActualVim/neo.py", line 127, in _setup
    self.nv = neovim.attach('child', argv=[NEOVIM_PATH, '--embed', '-n'] + args)
  File "/Users/mark/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/__init__.py", line 109, in attach
    return Nvim.from_session(session).with_decode(decode)
  File "/Users/mark/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/nvim.py", line 51, in from_session
    channel_id, metadata = session.request(b'vim_get_api_info')
  File "/Users/mark/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 107, in request
    raise IOError('EOF')
OSError: EOF
```

**Comment by mjedmonds** [comment]
This is due to an out-of-date neovim install. Installing the latest version fixed this for me.
