### ISSUE TITLE
Failed to save undo information

### ISSUE THREAD

**Issue by axsuul** [lunixbochs/ActualVim#138]
Using latest `master` branch and neovim `0.2.2` on macOS High Sierra. The path to my `nvim` is correct (`/usr/local/bin/nvim`). I'm running into some startup errors I believe since this is showing up in the console. Furthermore, I can't move my cursor or do anything unless I remove the ActualVim package:

```
ActualVim: using nvim binary path: /usr/local/bin/nvim
ActualVim: Error during nvim setup.
Traceback (most recent call last):
  File "/Users/axsuul/Library/Application Support/Sublime Text 3/Packages/ActualVim/neo.py", line 88, in plugin_loaded
    neovim_loaded()
  File "/Users/axsuul/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 24, in neovim_loaded
    ActualVim.enable()
  File "/Users/axsuul/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 139, in enable
    av.activate()
  File "/Users/axsuul/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 273, in activate
    self.sync_to_vim()
  File "/Users/axsuul/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 349, in sync_to_vim
    self.buf[:] = text
  File "/Users/axsuul/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/buffer.py", line 73, in __setitem__
    return self._set_lines(start, end, False, lines)
  File "/Users/axsuul/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/buffer.py", line 39, in _set_lines
    return self.request_raw('nvim_buf_set_lines', start, end, strict, lines)
  File "/Users/axsuul/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/common.py", line 47, in request_raw
    return self._session.request_raw(name, self._session._to_nvim(self), *args, **kwargs)
  File "/Users/axsuul/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/nvim.py", line 110, in request_raw
    return self._session.request(name, *args, **kwargs)
  File "/Users/axsuul/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 110, in request
    raise self.error_wrapper(err)
ActualVim.lib.neovim.api.nvim.NvimError: b'Failed to save undo information'
ActualVim: request "enter" failed: buf:1 has no view
```

Any suggestions?

**Comment by lunixbochs** [comment]
Did it work in the past? Do you have anything in your init.vim? I'm not sure what that error means (I'm not as familiar with neovim internals) but it's happening the very first time I sync the buffer to neovim.

I suspect it might be that you've reenabled undo files in your vim config and they can't save at the current path, which could be sometimes fixed by me switching to BufReadCmd.

You can also use g:actualvim as a boolean in your init.vim to disable sections only when in actualvim.

**Comment by axsuul** [comment]
Thanks for the lightning fast response! Didn't occur to me to debug my config 👍 

It looks like it was activating NERDTree that was causing the issue. No more startup errors and it seems to be working once I wrapped it between a `if !g:actualvim` block.
