### ISSUE TITLE
ActualVim: request "enter" failed: buf:530 has no view

### ISSUE THREAD

**Issue by timotheecour** [lunixbochs/ActualVim#159]
I'm getting a ton of these:
```
ActualVim: request "enter" failed: buf:530 has no view
ActualVim: request "enter" failed: buf:531 has no view
ActualVim: request "enter" failed: buf:532 has no view
ActualVim: request "enter" failed: buf:533 has no view
```
I have a bunch of buffers in sublime text that are no saved or are not mapped to a file; is that why? if so, ActualVim should perhaps be disabled for these?

**Comment by lunixbochs** [comment]
No, this is a harmless race condition each time ActualVim creates a buffer - vim tries to focus it, and it's not associated with a Sublime buffer yet.

**Comment by timotheecour** [comment]
- [ ] how about making that clear in msg? eg: `ActualVim: request "enter" failed: buf:530 has no view [harmless warning]`
- [ ] I have a feeling starting sublime (when i have a lot of opened files) is significantly slower with ActualVim enabled; is that expected?

**Comment by lunixbochs** [comment]
actualvim doesn't load a file until you focus it for the first time, so the startup speed should be independent of number of files

**Comment by 42a375562621634d5231e583caba7375** [comment]
Same error here. I'm on Sublime Text 3.1.1 Build 3176. No idea on how to even see AcutalVim in action.

**Comment by darthmall** [comment]
I sometimes get the same error when I'm creating a new file with the context menu in the sidebar. Here's the accompanying stacktrace:

```python
ActualVim: request "enter" failed: buf:30 has no view
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 462, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 483, in <lambda>
    run_callback(name, vel, lambda: vel.__class__.__dict__[name](vel))
  File "/home/evan/.config/sublime-text-3/Packages/ActualVim/actual.py", line 84, in on_activated
    self.v.activate()
  File "/home/evan/.config/sublime-text-3/Packages/ActualVim/view.py", line 278, in activate
    self.buf = neo.vim.buf_new(self)
  File "/home/evan/.config/sublime-text-3/Packages/ActualVim/neo.py", line 276, in buf_new
    self.cmd('enew')
  File "/home/evan/.config/sublime-text-3/Packages/ActualVim/neo.py", line 258, in cmd
    return self.nv.command_output(*args, **kwargs)
  File "/home/evan/.config/sublime-text-3/Packages/ActualVim/lib/neovim/api/nvim.py", line 225, in command_output
    return self.request('nvim_command_output', string)
  File "/home/evan/.config/sublime-text-3/Packages/ActualVim/lib/neovim/api/nvim.py", line 134, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/evan/.config/sublime-text-3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 103, in request
    v = self._yielding_request(method, args, timeout=kwargs.pop('timeout', 0.25))
  File "/home/evan/.config/sublime-text-3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 164, in _yielding_request
    return q.get(timeout=timeout)
  File "./python3.3/queue.py", line 175, in get
queue.Empty
ActualVim: request "enter" failed: buf:30 has no view
```
After which, ActualVim stops responding in any of my tabs. I can't enter insert mode or move the cursor; some Sublime Text's keybindings, such as `ctrl+s`, also stop working, while others like `ctrl+shift+p` continue to work.

If I close all of my open tabs and then recreate the file, ActualVim starts responding again.

**Comment by darthmall** [comment]
Looks like just like an empty vim buffer:

```
>>> print(str(neo.vim.screen))
  1                                                                                                                   
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
~                                                                                                                     
 NORMAL                                                                                       [unix]  100% ☰    0:  1 
             2 context:
```
