### ISSUE TITLE
"Error during nvim setup" in ./python3.3/queue.py

### ISSUE THREAD

**Issue by evanleck** [lunixbochs/ActualVim#168]
Hello! I _think_ I've got everything set up right (macOS 10.14.1, neovim 0.3.1 installed via Homebrew, and Sublime Text 3.1.1 build 3176) but I get this error message when starting up Sublime:

```
ActualVim: using nvim binary path: /usr/local/bin/nvim
ActualVim: Error during nvim setup.
Traceback (most recent call last):
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/neo.py", line 84, in plugin_loaded
    neovim_loaded()
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 25, in neovim_loaded
    ActualVim.enable()
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 147, in enable
    av.activate()
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 291, in activate
    self.set_path(path)
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 602, in set_path
    self.buf.name = path
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/buffer.py", line 129, in name
    return self.request('nvim_buf_set_name', value)
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/common.py", line 44, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/nvim.py", line 134, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 103, in request
    v = self._yielding_request(method, args, timeout=kwargs.pop('timeout', 0.25))
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 164, in _yielding_request
    return q.get(timeout=timeout)
  File "./python3.3/queue.py", line 175, in get
queue.Empty
```

I can load up the same files using `nvim` in the terminal just fine.

Thanks for taking a look!

**Comment by lunixbochs** [comment]
Do you have an init.vim? This error can happen if there’s some kind of blocking UI on startup.

**Comment by evanleck** [comment]
Yeah, I have the following in my init.vim, per [neovim's documentation](https://neovim.io/doc/user/nvim.html#nvim-from-vim):

```
set runtimepath^=~/.vim runtimepath+=~/.vim/after
let &packpath = &runtimepath
source ~/.vimrc
```

And my vimrc:

```
" My Vim configuration, inspired in part by:
"
" 1. https://statico.github.io/vim3.html and https://github.com/statico/dotfiles/blob/master/.vim/vimrc
" 2. https://tomjwatson.com/blog/vim-tips/
"
"
" Specify a directory for plugins
call plug#begin('~/.vim/plugged')

" Plugins
Plug '/usr/local/opt/fzf'
Plug 'airblade/vim-gitgutter'
Plug 'chriskempson/base16-vim'
Plug 'docunext/closetag.vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'her/central.vim'
Plug 'junegunn/fzf.vim'
Plug 'mileszs/ack.vim'
Plug 'sheerun/vim-polyglot'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-vinegar'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'w0rp/ale'

" Initialize plugin system
call plug#end()

" From https://github.com/rakr/vim-one
" Credit joshdick
" Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
" If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
" (see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
if (empty($TMUX))
  if (has("nvim"))
  " For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  " For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  " Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  "  < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif

" Because we're in the future.
set nocompatible

" Because everything is UTF-8.
set encoding=utf-8

" Disable line wrapping.
set nowrap

" Essential for filetype plugins.
filetype plugin indent on

" Because syntax matters.
syntax on

" Color scheme setup.
" colorscheme base16-eighties
" colorscheme base16-flat
" colorscheme base16-nord
colorscheme base16-oceanicnext
" colorscheme base16-onedark

" Magic line numbers.
set number relativenumber

" Indentation.
set autoindent smartindent breakindent
set breakindentopt=shift:2

" White space, tabs, and text.
set list                    " Show whitespace as special chars - see listchars
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:· " Unicode characters for various things
set autoread                " Don't bother me when a file changes
set expandtab               " No tabs
set shiftround              " Shift to certain columns, not just n spaces
set shiftwidth=2            " Number of spaces to shift for autoindent or >,<
set ignorecase              " Ignore case by default.
set smartcase               " Lets you search for ALL CAPS
set softtabstop=2           " Spaces 'feel' like tabs
set tabstop=2               " The One True Tab
set textwidth=100           " 100 is the new 80
set wildmenu                " Show possible completions on command line
set wildmode=list:longest,full " List all options and complete
set wildignore=*.class,*.o,*~,*.pyc,.git,node_modules  " Ignore certain files in tab-completion
set lazyredraw              " Redraw only when needed.
set showmatch               " highlight matching [{()}]
set incsearch               " search as characters are entered
set hlsearch                " highlight matches

" Remove all the scrollbars.
set guioptions-=r
set guioptions-=l
set guioptions-=R
set guioptions-=L

" Jump to last cursor position unless it's invalid or in an event handler
" https://github.com/garybernhardt/dotfiles/blob/master/.vimrc#L95
autocmd BufReadPost *
  \ if line("'\"") > 0 && line("'\"") <= line("$") |
  \   exe "normal g`\"" |
  \ endif

" Disable balloon tooltips. Always.
autocmd BufNewFile,BufRead * set noballooneval

" YAML is indentation-sensitive.
autocmd Syntax yaml setlocal foldmethod=indent

" Set the fold method to syntax for certain file types.
autocmd Syntax xml,html,xhtml,ruby,javascript,json,eruby setlocal foldmethod=syntax

" Unfold everything for the above syntaxes.
autocmd Syntax xml,html,xhtml,ruby,javascript,json,eruby,yaml,typescript normal zR

" Makefiles should always have actual tab characters.
autocmd Syntax make setlocal noexpandtab

" Wrap markdown text.
autocmd Syntax markdown setlocal wrap

" Font options.
set guifont=Fira\ Code:h11
set linespace=2 " Ups the line-height.

" Turn off linewise keys.
nmap j gj
nmap k gk

" Delete all buffers.
nnoremap <Leader>bd :bufdo :bd<CR>

" Use the space key to toggle folds.
nnoremap <space> za
vnoremap <space> zf

" Key combos
nnoremap ; :Buffers<CR>
nnoremap <Leader>c :term<CR>
nnoremap <Leader>r :Tags<CR>
nnoremap <Leader>b :BTags<CR>
nnoremap <Leader>t :Files<CR>
nnoremap <Leader>a :Ack!<Space>

" Because lazy.
nnoremap <Leader>w :w<CR>
nnoremap <Leader>q :q<CR>

" Like Command+, but for Vim.
nnoremap <Leader>, :e ~/.vimrc<CR>

" Splits
nnoremap <Leader>vs :vs<CR>
nnoremap <Leader>sp :sp<CR>

" Fugitive
nnoremap <Leader>gb :Gblame<CR>
nnoremap <Leader>gc :Gcommit<CR>
nnoremap <Leader>gd :Gdiff<CR>
nnoremap <Leader>gs :Gstatus<CR>

" For quick session saving and restoring.
nnoremap <Leader>ss :mksession!<CR>
nnoremap <Leader>sl :source Session.vim<CR>

" Sort visually selected lines.
vnoremap <Leader>s :sort<CR>

" Turn off search highlight.
nnoremap <Leader><space> :nohlsearch<CR>

" Insert newlines.
" Via https://stackoverflow.com/questions/6765211/vim-command-to-insert-blank-line-in-normal-mode#6765349
nnoremap <silent> [<space> :pu! _<cr>:']+1<cr>
nnoremap <silent> ]<space> :pu _<cr>:'[-1<cr>

" Keep ack.vim from opening the first result.
cnoreabbrev Ack Ack!

" Taken from https://github.com/garybernhardt/dotfiles/blob/master/.vimrc
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" MULTIPURPOSE TAB KEY
" Indent if we're at the beginning of a line. Else, do completion.
""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
function! InsertTabWrapper()
    let col = col('.') - 1
    if !col || getline('.')[col - 1] !~ '\k'
        return "\<tab>"
    else
        return "\<c-p>"
    endif
endfunction
inoremap <expr> <tab> InsertTabWrapper()
inoremap <s-tab> <c-n>

" Use Silver Searcher for ack.vim
let g:ackprg = 'ag --vimgrep'

" Customize fzf colors to match your color scheme
let g:fzf_colors =
\ { 'fg':      ['fg', 'Normal'],
  \ 'bg':      ['bg', 'Normal'],
  \ 'hl':      ['fg', 'Comment'],
  \ 'fg+':     ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':     ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':     ['fg', 'Statement'],
  \ 'info':    ['fg', 'PreProc'],
  \ 'border':  ['fg', 'Ignore'],
  \ 'prompt':  ['fg', 'Conditional'],
  \ 'pointer': ['fg', 'Exception'],
  \ 'marker':  ['fg', 'Keyword'],
  \ 'spinner': ['fg', 'Label'],
  \ 'header':  ['fg', 'Comment'] }

" Command to generate tags file
let g:fzf_tags_command = 'ctags'

" ALE
let g:ale_lint_on_text_changed = 'never'
let g:ale_linters = { 'eruby': ['erubi'], 'java': [] }
let g:ale_sign_column_always = 1
let g:ale_sign_error = '✗'
let g:ale_sign_warning = '▲'

highlight link ALEWarningSign String
highlight link ALEErrorSign Title

nnoremap ]l :ALENextWrap<CR>
nnoremap [l :ALEPreviousWrap<CR>

" Set this. Airline will handle the rest.
let g:airline#extensions#ale#enabled = 1

let g:airline_theme='base16_oceanicnext'
" let g:airline_theme='base16_nord'
" let g:airline_theme='base16_flat'

" Resize panes when window/terminal gets resize
autocmd VimResized * :wincmd =
```

**Comment by evanleck** [comment]
It starts up fine and some basic movement and editing works, but if I try to write the file with `:w` I get what looks like the same error:

```
Traceback (most recent call last):
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 684, in on_done
    _, ready = neo.vim.press('<cr>', onready)
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/neo.py", line 311, in press
    res = self.nv.request('nvim_get_mode') or {}
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/nvim.py", line 134, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 103, in request
    v = self._yielding_request(method, args, timeout=kwargs.pop('timeout', 0.25))
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 164, in _yielding_request
    return q.get(timeout=timeout)
  File "./python3.3/queue.py", line 175, in get
queue.Empty
```

**Comment by lunixbochs** [comment]
In this case does the error actually have an effect or can you continue using the editor?

**Comment by evanleck** [comment]
The editor continues working.

**Comment by lunixbochs** [comment]
You can also view the screen in a roundabout way:
```
from actualvim import neo
print(str(neo.vim.screen))
```

**Comment by lunixbochs** [comment]
Since the editor continues working, that’s a symptom of the neovim RPC hanging for a short time but not actually breaking anything.

**Comment by evanleck** [comment]
Interesting. What's got me perplexed then is why neovim works fine with my init.vim but this is crashing... Does anything in my config stand out as incompatible? I use plugged for plugins and most everything else is shortcut configurations.

**Comment by lunixbochs** [comment]
Have you tried printing the screen while it's hung with your init.vim as I suggested?

**Comment by evanleck** [comment]
Sorry, no, I saw you posted that but I wasn't sure where to paste it. Does that go in the Sublime Text console? I tried it there but I get this error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'actualvim'
```

**Comment by lunixbochs** [comment]
Oh, capitalize ActualVim

**Comment by evanleck** [comment]
```
>>> from ActualVim import neo
>>> print(str(neo.vim.screen))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'vim'
```

**Comment by evanleck** [comment]
```
ActualVim: Error during nvim setup.
Traceback (most recent call last):
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/neo.py", line 84, in plugin_loaded
    neovim_loaded()
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 25, in neovim_loaded
    ActualVim.enable()
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 147, in enable
    av.activate()
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 291, in activate
    self.set_path(path)
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 602, in set_path
    self.buf.name = path
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/buffer.py", line 129, in name
    return self.request('nvim_buf_set_name', value)
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/common.py", line 44, in request
    return self._session.request(name, self, *args, **kwargs)
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/nvim.py", line 134, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 103, in request
    v = self._yielding_request(method, args, timeout=kwargs.pop('timeout', 0.25))
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 164, in _yielding_request
    return q.get(timeout=timeout)
  File "./python3.3/queue.py", line 175, in get
queue.Empty
Printing vim.screen
  7   message  "",                                                                                                                                                                                     
  6 ‹"properties":{                                                                                                                                                                                    
  5 ‹  "terms":[                                                                                                                                                                                       
  4 ‹    {                                                                                                                                                                                             
  3 ‹      "id":1,                                                                                                                                                                                     
  2 ‹      "display":[                                                                                                                                                                                 
  1 ‹        "ENROLLMENT",                                                                                                                                                                             
11  ‹        "ACTIVATION",s":true,                                                                                                                                                                     
  1 ‹        "HELP",                                                                                                                                                                                   
  2 ‹        "MOBILE",                                                                                                                                                                                 
  3 ‹        "WEB"                                                                                                                                                                                     
  4 ‹      ],                                                                                                                                                                                          
  5 ‹      "name":"eSign Agreement",                                                                                                                                                                   
  6 ‹      "type":"ESIGN_AGREEMENT",                                                                                                                                                                   
  7 ‹      "url":"https://my/term1/url"                                                                                                                                                                
  8 ‹    },                                                                                                                                                                                            
  9 ‹    {                                                                                                                                                                                             
 10 ‹      "id":2,                                                                                                                                                                                     
 11 ‹      "display":[                                                                                                                                                                                 
 12 ‹        "CHECK_CAPTURE",                                                                                                                                                                          
 13 ‹        "HELP",                                                                                                                                                                                   
 14 ‹        "MOBILE"                                                                                                                                                                                  
 15 ‹      ],                                                                                                                                                                                          
 16 ‹      "name":"eSign Agreement",                                                                                                                                                                   
 17 ‹      "type":"ESIGN_AGREEMENT",                                                                                                                                                                   
 18 ‹      "url":"https://my/term2/url"                                                                                                                                                                
 NORMAL  [+]                                                                                                                                                                   [unix]   15% ☰   11: 12 
                                                                                                                                                                                                       
lang_service_enabled: True
Path of tsserver.js: /Users/evan/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsserver.js
Path of tsc.js: /Users/evan/Library/Application Support/Sublime Text 3/Packages/TypeScript/tsserver/tsc.js
Trying to spawn node executable from: /Users/evan/.asdf/shims/node
ref view not found
ActualVim: request "enter" failed: buf:1 has no view
```

The JSON after "Printing vim.screen" is the file I'm editing.

**Comment by lunixbochs** [comment]
Oh, it's possible all that's happening here is actualvim's timeout is too low for however long it takes your init.vim to run.

**Comment by lunixbochs** [comment]
`    v = self._yielding_request(method, args, timeout=kwargs.pop('timeout', 0.25))`
You can try just making this number bigger, maybe 3s?

**Comment by evanleck** [comment]
Cranking it up to 3 seconds gets the file to load, but attempting to save the file with `:w` still yields this:

```
Traceback (most recent call last):
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 684, in on_done
    _, ready = neo.vim.press('<cr>', onready)
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/neo.py", line 313, in press
    res = self.nv.request('nvim_get_mode') or {}
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/nvim.py", line 134, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 103, in request
    v = self._yielding_request(method, args, timeout=kwargs.pop('timeout', 3))
  File "/Users/evan/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 164, in _yielding_request
    return q.get(timeout=timeout)
  File "./python3.3/queue.py", line 175, in get
queue.Empty
```

**Comment by lunixbochs** [comment]
nvim_get_mode isn't supposed to block, maybe bug the neovim folks about that

**Comment by lunixbochs** [comment]
@justinmk

**Comment by justinmk** [comment]
It's best-effort. We can't truly guarantee it won't block until we actually enable API calls during wait-for-input, which we plan to do very soon.

**Comment by lunixbochs** [comment]
@evanleck ok, so on neo.py line 313, maybe add a timeout like this:
```
try:
    res = self.nv.request('nvim_get_mode', timeout=0.1) or {}
    ready = not res.get('blocking', True)
except Exception:
    ready = False
```

**Comment by lunixbochs** [comment]
It seems like you reverted the 3s timeout. These two fixes were separate.

**Comment by evanleck** [comment]
Damn, I did, sorry. Just put that back and it appears to boot up without error but the editor appears frozen i.e. I can't move around with `j` `k` etc.

```
ref view not found
ActualVim: using nvim binary path: /usr/local/bin/nvim
ActualVim: nvim started in 1531.00ms
ActualVim: request "enter" failed: buf:1 has no view
```

**Comment by lunixbochs** [comment]
Still frozen if you make a new file from sublime’s ui and try to edit that?

**Comment by evanleck** [comment]
The cursor doesn't appear to move but e.g. pressing "^ D" deletes the current line though the cursor never appears at the start of the line before deleting. I can enter insert mode but the cursor doesn't change its appearance... it's weird.

**Comment by lunixbochs** [comment]
Maybe 0.1s was too low for nvim_get_mode with your settings.
