### ISSUE TITLE
<leader> key not working

### ISSUE THREAD

**Issue by gour** [lunixbochs/ActualVim#173]
Hello,

I've the following in my .vimrc:

```
let mapleader = ","
```

which is sourced in `init.vim`.

I'm trying to use it with e.g. [vim-asciidoc](https://github.com/dahu/vim-asciidoc) plugin where e.g.

`<Leader>2` should produce level-2 heading in the file and it works in both (neo)vim, but not in ST3.

Any hint?

I use neovim-0.34 under Manjaro (Arch) Linux...

**Comment by lunixbochs** [comment]
Have you tried the actualvim master branch?

**Comment by gour** [comment]
> Have you tried the actualvim master branch?

I've tried to clone into  `~/.config/sublime-text-3/Packages/`, but it does not work.

Here is what I get in console:

```
[...]
reloading plugin ActualVim.actual
reloading plugin ActualVim.edit
reloading plugin ActualVim.neo
reloading plugin ActualVim.screen
reloading plugin ActualVim.settings
reloading plugin ActualVim.view
plugins loaded
Traceback (most recent call last):
  File "/home/gour/.config/sublime-text-3/Packages/ActualVim/view.py", line 109, in get
    m = cls(view)
  File "/home/gour/.config/sublime-text-3/Packages/ActualVim/view.py", line 94, in __init__
    bytes = lfd.get('bytes', -1)
AttributeError: 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/home/gour/.config/sublime-text-3/Packages/ActualVim/view.py", line 109, in get
    m = cls(view)
  File "/home/gour/.config/sublime-text-3/Packages/ActualVim/view.py", line 94, in __init__
    bytes = lfd.get('bytes', -1)
AttributeError: 'NoneType' object has no attribute 'get'
ActualVim: using nvim binary path: /usr/bin/nvim
ActualVim: nvim started in 489.97ms
ActualVim: request "enter" failed: buf:1 has no view
reloading settings Packages/User/ActualVim.sublime-settings
Package Control: Skipping automatic upgrade, last run at 2019-03-16 18:34:12, next run at 2019-03-16 19:34:12 or after
ActualVim: request "enter" failed: buf:2 has no view
```

Any hint?

**Comment by lunixbochs** [comment]
try restarting sublime? could be case sensitivity? did you remove the package control version first?

**Comment by gour** [comment]
> try restarting sublime? 

It does not help.

> could be case sensitivity? 

What do you mean? Same setup does work in plain (neo)vim

>  did you remove the package control version first?

Yes.

Any idea how to debug it?

**Comment by lunixbochs** [comment]
What do your actualvim user settings look like?

**Comment by gour** [comment]
> What do your actualvim user settings look like?

```
{
	"bufopts":
	{
		"completefunc": "ActualVimComplete"
	},
	"enabled": true,
	"large_file_disable":
	{
		"bytes": 52428800,
		"lines": 50000
	},
	"neovim_args":
	[
		"--cmd",
		"let g:actualvim = 1"
	],
	"neovim_path": "",
	"settings":
	{
		"sublime":
		{
			"inverse_caret_state": false
		},
		"vim":
		{
			"bell":
			{
				"color_scheme": "Packages/ActualVim/Bell.tmTheme",
				"duration": 0.001
			},
			"inverse_caret_state": false,
			"modes":
			{
				"all insert":
				{
				},
				"all visual":
				{
				},
				"command":
				{
					"inverse_caret_state": true
				},
				"insert":
				{
				},
				"normal":
				{
					"av:ctrl+n": true,
					"av:ctrl+s": true,
					"av:ctrl+w": true,
					"inverse_caret_state": true
				},
				"replace":
				{
				},
				"visual":
				{
				},
				"visual block":
				{
				},
				"visual line":
				{
				}
			}
		}
	},
	"settings_priority": "sublime",
	"smooth_scroll": false
}
```

**Comment by lunixbochs** [comment]
Are you still getting the `lfd` error in console?

**Comment by gour** [comment]
> Are you still getting the lfd error in console?

No, but the behaviour is certainly erratic...sometime I am able to get the heading, but it looks as it depends on the Moon's phase and not on my keypresses. :-(
