### ISSUE TITLE
Sporadic starts and backtraces.

### ISSUE THREAD

**Issue by sinkr** [lunixbochs/ActualVim#174]
Sometimes ST starts up and initializes neovim correctly, other times it gives this or similar, with no rhyme or reason.  I would really love for ActualVim + ST to be stable, but to date it's been a very mixed bag. 
Any ideas?

`plugins loaded
Loaded VimModelines
ActualVim: using nvim binary path: /usr/local/bin/nvim
ActualVim: Error during nvim setup.
Traceback (most recent call last):
  File "/Users/robert/Library/Application Support/Sublime Text 3/Packages/ActualVim/neo.py", line 79, in plugin_loaded
    vim._setup()
  File "/Users/robert/Library/Application Support/Sublime Text 3/Packages/ActualVim/neo.py", line 154, in _setup
    self.nv.options['hidden'] = True
  File "/Users/robert/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/common.py", line 90, in __setitem__
    self._set(key, value)
  File "/Users/robert/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/nvim.py", line 134, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/robert/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 103, in request
    v = self._yielding_request(method, args, timeout=kwargs.pop('timeout', 0.25))
  File "/Users/robert/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 164, in _yielding_request
    return q.get(timeout=timeout)
  File "./python3.3/queue.py", line 175, in get
queue.Empty
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2019-04-04 14:30:39, next run at 2019-04-04 15:30:39 or after`

**Comment by lunixbochs** [comment]
Do you have much stuff in your init.vim? It's probably timing out waiting for neovim to start up

**Comment by sinkr** [comment]
Hey Ryan,

Thank you for the response!


Yes, I'm sure I do have a bit in my init.vim.  Is there a way to increase
the timeout?  I've seen discussion on this, but am uncertain where to put
it in the ActualVim settings.

Thanks again!

**Comment by lunixbochs** [comment]
https://github.com/lunixbochs/ActualVim/issues/168

**Comment by lunixbochs** [comment]
There's no setting for this atm. You can edit the timeout in code: https://github.com/lunixbochs/ActualVim/issues/168#issuecomment-445059718

**Comment by sinkr** [comment]
Thank you very much.  Are you accepting donations / support for development
of ActualVim?  I'd love to see it get some attention.

Regards,

-R.

**Comment by lunixbochs** [comment]
I have a patreon: patreon.com/lunixbochs
I’m not using it as my main editor right now so I’d need advice on the main pain points.

**Comment by sinkr** [comment]
Subscribed!

I think you answered a major question re: stability with the timeout
update.  I guess I'd be interested in understanding the internals more so
that perhaps I could be in a position to surface more functionality, like
the visual search and replace functionality that come to mind.

Regards,

-R.

**Comment by lunixbochs** [comment]
Visual search/replace should work, it just won't highlight stuff by default because the remote highlight api in neovim isn't great. You need to enable the 'highlights' setting to see them: https://github.com/lunixbochs/ActualVim/issues/148#issuecomment-377286702

@justinmk is there a better highlights API yet?

**Comment by sinkr** [comment]
OK, I did try turning the highlighting on as prescribed in #148, however,
it's definitely not usable in its present form, IMO.

**Comment by lunixbochs** [comment]
What sort of specific issues are you having with it that prevent it from being usable?

**Comment by sinkr** [comment]
Here's an example screenshot.

![image](https://user-images.githubusercontent.com/696374/55756921-b09c5700-5a20-11e9-9efc-f65bfc52f870.png)

**Comment by justinmk** [comment]
> @justinmk is there a better highlights API yet?

Somewhat,  see `:help ui-ext-options` in Nvim 0.3.4.  There's a new UI extension called `ext_hlstate`:

> The `ext_hlstate` extension allows to the UI to also receive a semantic description of the highlights active in a cell. In this mode highlights will be

That extension complements the new `ext_linegrid` extension which also helps performance and is better designed. It also separates the editor cursor from the "paint" cursor, which may be helpful to ActualVim. From `:help ui-linegrid`:

> The biggest change compared to previous revision is to use a single `grid_line` event to update the contents of a screen line (where the old protocol used a combination of cursor, highlight and text events)

- `ext_messages` extension will also be useful for ActualVim. 
- The startup "race" in older versions of Nvim is fixed in 0.3.4. Please read https://github.com/neovim/neovim/wiki/Following-HEAD#20180922

Future work / current progress:

- https://github.com/neovim/neovim/issues/9421 umbrella issue which contains current progress as well as discussion about highlights API
- [treesitter integration](https://github.com/neovim/neovim/pull/9219) will influence the shape of the highlights API
- API for visual selection is relatively easy compared to more advanced syntax/highlight API, and will be needed for the upcoming [GSoC](https://github.com/neovim/neovim/wiki/GSoC-2019-Ideas) work this summer.
