### ISSUE TITLE
Error in console when saving settings, cannot set nvim path

### ISSUE THREAD

**Issue by alexallan** [lunixbochs/ActualVim#175]
When attempting to install ActualVim, get error in console when saving settings and functionality not working. My setting file looks like this:
```
{
	"bufopts":
	{
		"completefunc": "ActualVimComplete"
	},
	"enabled": true,
	"large_file_disable":
	{
		"bytes": 52428800,
		"lines": 50000
	},
	"neovim_args":
	[
		"--cmd",
		"let g:actualvim = 1"
	],
	"neovim_path": "/Users/aa/Downloads/nvim-osx64/bin/nvim",
	"settings":
	{
		"sublime":
		{
			"inverse_caret_state": false
		},
		"vim":
		{
			"bell":
			{
				"color_scheme": "Packages/ActualVim/Bell.tmTheme",
				"duration": 0.001
			},
			"inverse_caret_state": false,
			"modes":
			{
				"all insert":
				{
				},
				"all visual":
				{
				},
				"command":
				{
					"inverse_caret_state": true
				},
				"insert":
				{
				},
				"normal":
				{
					"inverse_caret_state": true
				},
				"replace":
				{
				},
				"visual":
				{
				},
				"visual block":
				{
				},
				"visual line":
				{
				}
			}
		}
	},
	"settings_priority": "sublime",
	"smooth_scroll": false
}
```

And the console error is thus:
```
AttributeError: 'NoneType' object has no attribute 'name'
reloading settings Packages/User/ActualVim.sublime-settings
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 576, in on_post_save_async
    callback.on_post_save_async(v)
  File "/Users/aa/Library/Application Support/Sublime Text 3/Packages/ActualVim/actual.py", line 111, in on_post_save_async
    v.set_path(view.file_name())
  File "/Users/aa/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 602, in set_path
    self.buf.name = path
AttributeError: 'NoneType' object has no attribute 'name'
```

**Comment by lunixbochs** [comment]
Do you have more console output from startup?

**Comment by sammorley-short** [comment]
> Do you have more console output from startup? Did you just update the binary path? Restarting sublime might help.

I am having the same issue and restarting didn't help. My traceback from startup is: 
```
ActualVim: using nvim binary path: /usr/local/bin/nvim
ActualVim: Error during nvim setup.
Traceback (most recent call last):
  File "/Users/sms/Library/Application Support/Sublime Text 3/Packages/ActualVim/neo.py", line 79, in plugin_loaded
    vim._setup()
  File "/Users/sms/Library/Application Support/Sublime Text 3/Packages/ActualVim/neo.py", line 154, in _setup
    self.nv.options['hidden'] = True
  File "/Users/sms/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/common.py", line 90, in __setitem__
    self._set(key, value)
  File "/Users/sms/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/nvim.py", line 134, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/sms/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 103, in request
    v = self._yielding_request(method, args, timeout=kwargs.pop('timeout', 0.25))
  File "/Users/sms/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 164, in _yielding_request
    return q.get(timeout=timeout)
  File "./python3.3/queue.py", line 175, in get
queue.Empty
```

**Comment by lunixbochs** [comment]
That means something is wrong with neovim, either neovim can't be executed, or there's something in your init.vim that prevents startup.

**Comment by sammorley-short** [comment]
Ah, that's annoying. Any idea what it could be? Thanks a bunch for for your help!

**Comment by lunixbochs** [comment]
You might be able to get some info about what neovim is doing by inspecting the actualvim.neo.vim.screen object

**Comment by justinmk** [comment]
> or there's something in your init.vim that blocks or stalls startup.

Fixed in Nvim versions since September 2018, as long as the UI doesn't specify `--headless`. See https://github.com/neovim/neovim/wiki/Following-HEAD#20180922

**Comment by sammorley-short** [comment]
This seems to be the same issue as here: https://github.com/lunixbochs/ActualVim/issues/175 (same initialisation traceback), however unlike OP in that post, when I remove my `init.vim`, the package works as expected.

The offending lines in `init.vim` are the use of the deoplete package (installed with vim-plug):
```vimscript
call plug#begin('~/.config/nvim/plugged')
 Plug 'Shougo/deoplete.nvim',
call plug#end()
```

Or, the following line if the plugin directory in which `palenight.vim` exists has not been specified:
```vimscript 
colorscheme palenight " Sets the colour scheme
```

Also, in an attempt to bypass the `init.vim` file on load, I added the nvim arg `--clean`, but this didn't work either.

**Comment by sammorley-short** [comment]
Workaround:  adding `--noplugin` seems to prevent the bad plugin from loading, which works for now
