### ISSUE TITLE
:w freeze about 500ms with errors

### ISSUE THREAD

**Issue by doveC** [lunixbochs/ActualVim#177]
the console output is:

> Traceback (most recent call last):
  File "D:\Software\Sublime Text 3\sublime_plugin.py", line 576, in on_post_save_async
    callback.on_post_save_async(v)
  File "C:\Users\a1599\AppData\Roaming\Sublime Text 3\Packages\ActualVim\actual.py", line 111, in on_post_save_async
    v.set_path(view.file_name())
  File "C:\Users\a1599\AppData\Roaming\Sublime Text 3\Packages\ActualVim\view.py", line 602, in set_path
    self.buf.name = path
  File "C:\Users\a1599\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\api\buffer.py", line 129, in name
    return self.request('nvim_buf_set_name', value)
  File "C:\Users\a1599\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\api\common.py", line 44, in request
    return self._session.request(name, self, *args, **kwargs)
  File "C:\Users\a1599\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\api\nvim.py", line 134, in request
    res = self._session.request(name, *args, **kwargs)
  File "C:\Users\a1599\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\msgpack_rpc\session.py", line 103, in request
    v = self._yielding_request(method, args, timeout=kwargs.pop('timeout', 0.25))
  File "C:\Users\a1599\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\msgpack_rpc\session.py", line 164, in _yielding_request
    return q.get(timeout=timeout)
  File "./python3.3/queue.py", line 175, in get
queue.Empty

**Comment by lunixbochs** [comment]
Does the save work, and is everything else ok afterwards?

https://github.com/lunixbochs/ActualVim/issues/168 talks about diagnosing neovim hangs a bit.
