### ISSUE TITLE
Error during nvim setup: 'AsyncioEventLoop' object has no attribute '_on_stderr'

### ISSUE THREAD

**Issue by fritzr** [lunixbochs/ActualVim#178]
I'm experiencing a nearly identical error to #110, except that I'm on Windows 10 x86_64 and installing different versions of Nvim did NOT solve anything. All associated components are freshly installed, and I do not have an init.nvim:

Sublime Text 3.2.1 with embedded Python 3.3.6
I've tried the ActualVim tags 0.9.4, 0.9.10, and 0.9.17
I've tried NeoVim versions 0.2.2 and 0.3.{0,1,5,8}

The error I see from the Sublime Text console is:

```
reloading plugin ActualVim.actual
reloading plugin ActualVim.edit
reloading plugin ActualVim.neo
reloading plugin ActualVim.screen
reloading plugin ActualVim.settings
reloading plugin ActualVim.view
plugins loaded
ActualVim: using nvim binary path: E:\Programs\Neovim 0.2.2\bin\nvim-qt.exe
Exception in callback AsyncioEventLoop.pipe_data_received(2, b'Unknown opt...: n, cmd.\r\n')
handle: <Handle AsyncioEventLoop.pipe_data_received(2, b'Unknown opt...: n, cmd.\r\n')>
Traceback (most recent call last):
  File "C:\Users\pwnzo_000\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\asyncio\events.py", line 126, in _run
    self._callback(*self._args)
  File "C:\Users\pwnzo_000\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\msgpack_rpc\event_loop\asyncio.py", line 59, in pipe_data_received
    self._on_stderr(data)
AttributeError: 'AsyncioEventLoop' object has no attribute '_on_stderr'
ActualVim: Error during nvim setup.
Traceback (most recent call last):
  File "C:\Users\pwnzo_000\AppData\Roaming\Sublime Text 3\Packages\ActualVim\neo.py", line 79, in plugin_loaded
    vim._setup()
  File "C:\Users\pwnzo_000\AppData\Roaming\Sublime Text 3\Packages\ActualVim\neo.py", line 126, in _setup
    self.nv = neovim.attach('child', argv=[NEOVIM_PATH, '--embed', '-n'] + args)
  File "C:\Users\pwnzo_000\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\__init__.py", line 109, in attach
    return Nvim.from_session(session).with_decode(decode)
  File "C:\Users\pwnzo_000\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\api\nvim.py", line 51, in from_session
    channel_id, metadata = session.request(b'vim_get_api_info')
  File "C:\Users\pwnzo_000\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\msgpack_rpc\session.py", line 109, in request
    raise IOError('EOF')
OSError: EOF
```

Instead of the VIM startup text that mjedmonds sees, note that I see `b'Unknown opt...: n, cmd.\r\n'` as the pipe_data being received - not sure if this indicates two errors are actually at play here?

With this error, I cannot affect the Sublime buffers at all - I'd appreciate any ideas for a workaround.

**Comment by lunixbochs** [comment]
This error is coming from inside the neovim python library. I assume the startup text is the problem - @justinmk?

Do you have an init.vim in place with neovim? Have you tried without it?

**Comment by justinmk** [comment]
> ActualVim: using nvim binary path: E:\Programs\Neovim 0.2.2\bin\nvim-qt.exe

That's a GUI. It should use `nvim.exe` directly.

**Comment by fritzr** [comment]
@justinmk Ah-hah! For some reason I thought I read the path needed to point to the GUI executable... But that doesn't make much sense when I think about it. 

I'll try this tonight but I assume it will work so I'll close the issue for now. Thanks!

**Comment by justinmk** [comment]
To avoid this in the future,  ActualVim could check that the user-provided binary path responds to `--api-info` to verify that the binary is an actual working `nvim` binary.
