### ISSUE TITLE
After months of working, it just now freezes

### ISSUE THREAD

**Issue by sinkr** [lunixbochs/ActualVim#181]
Let me know what I can do to help debug--I'm a paid supporter for ActualVim.

**Comment by sinkr** [comment]
Hy Ryan,

Thanks for responding!

I have a neovim init, however when I remove it, the same happens (ActualVim
and ST come up unresponsive in the editor--ST's GUI still works).

I get nothing when I type; no text and VIM commands do not respond, either.

My NeoVim version:  v0.4.0-1713-g1852dfdf9

OS: macOS Catalina

Here seems to be the error, however, with this error I get to use the
editor text area, however, there is no neovim functionality.  My experience
seems to oscillate between no neovim, but can use Sublime Text, or neovim
and no text functionality:

ActualVim: using nvim binary path: /usr/local/bin/nvim
ActualVim: Error during nvim setup.
Traceback (most recent call last):
  File "/Users/robert/Library/Application Support/Sublime Text
3/Packages/ActualVim/neo.py", line 79, in plugin_loaded
    vim._setup()
  File "/Users/robert/Library/Application Support/Sublime Text
3/Packages/ActualVim/neo.py", line 154, in _setup
    self.nv.options['hidden'] = True
  File "/Users/robert/Library/Application Support/Sublime Text
3/Packages/ActualVim/lib/neovim/api/common.py", line 90, in __setitem__
    self._set(key, value)
  File "/Users/robert/Library/Application Support/Sublime Text
3/Packages/ActualVim/lib/neovim/api/nvim.py", line 134, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/robert/Library/Application Support/Sublime Text
3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 103, in
request
    v = self._yielding_request(method, args, timeout=kwargs.pop('timeout',
2))
  File "/Users/robert/Library/Application Support/Sublime Text
3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 164, in
_yielding_request
    return q.get(timeout=timeout)
  File "./python3.3/queue.py", line 175, in get
queue.Empty
Emmet: No need to update PyV8
Package Control: Skipping automatic upgrade, last run at 2019-10-29
13:55:59, next run at 2019-10-29 14:55:59 or after

**Comment by lunixbochs** [comment]
The queue.get() timeout means we’re sending requests to neovim and it’s not responding. The next step would be to show the neovim screen.

There are some general debugging steps in this thread https://github.com/lunixbochs/ActualVim/issues/168#issuecomment-444981331

Try adding a print as described here so we can see the screen:

https://github.com/lunixbochs/ActualVim/issues/168#issuecomment-445052993

**Comment by sinkr** [comment]
Sorry, I feel like I've missed something here, but this is what I get:

>>> print(str(vim.screen))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'vim' is not defined

**Comment by lunixbochs** [comment]
You need to add it to the actualvim source at the linked position, not just run it in the repl.

**Comment by sinkr** [comment]
Ugh, thanks for the response.  I think I'm going to give up on ActualVim.
I need to get real work done.

Regards,

-R.

**Comment by lunixbochs** [comment]
Can you at least confirm that nvim itself works from a terminal?

**Comment by sinkr** [comment]
Hi Ryan,

Yes, it works just fine from the CLI and from within VimR and MacVim.

**Comment by sammorley-short** [comment]
@sinkr: I was having a similar issue as you, which appears to be due to a bad plugin breaking ActualVim (see https://github.com/lunixbochs/ActualVim/issues/175). My workaround was to add `--noplugin` to the `"neovim_args"` section in the settings. Hopefully this solves your issue too.

**Comment by sinkr** [comment]
> @sinkr: I was having a similar issue as you, which appears to be due to a bad plugin breaking ActualVim (see #175). My workaround was to add `--noplugin` to the `"neovim_args"` section in the settings. Hopefully this solves your issue too.

@sammorley-short thanks for the response.  I can see where that would work, however, I've given up on ActualVim since it's more or less abandonware.

**Comment by Strangehill** [comment]
> @sinkr: I was having a similar issue as you, which appears to be due to a bad plugin breaking ActualVim (see #175). My workaround was to add `--noplugin` to the `"neovim_args"` section in the settings. Hopefully this solves your issue too.

This fixed it for me! 
Further, I pinpointed the problem the `Plugin 'SirVer/ultisnips'` so I plan to comment out this particular plugin momentarily when starting Sublime.
(So I can keep using ultisnips directly in neovim, even though it's the buggiest of the plugins I've got installed)
Is there any way to just add this plugin to a black list in ActualVim settings? (feature request?)

**Comment by Strangehill** [comment]
@sinkr: I was having a similar issue as you, which appears to be due to a bad plugin breaking ActualVim (see #175). My workaround was to add --noplugin to the "neovim_args" section in the settings. Hopefully this solves your issue too.

This fixed it for me!
Further, I pinpointed the problem to two plugins 'SirVer/ultisnips' and 'vim-airline/vim-airline' so I plan to comment out these particular plugins momentarily when starting Sublime.
(using ultisnips directly in neovim is very buggy, but I don't want to nix it entirely)
Is there any way to just add this plugin to a black list in ActualVim settings? (feature request?)
