### ISSUE TITLE
Error during nvim setup, OSError: EOF in session.py

### ISSUE THREAD

**Issue by gitAlwin** [lunixbochs/ActualVim#186]
Hello,

I get an error when the plugin is loaded: ```Error during nvim setup```. I realize that there is another issue (issue #185 ) which also reports this error. However, the Python traceback is not the same in these cases which is the reason I opened a separate issue. If it is in fact the same issue I apologize for creating a second issue concerning the same problem.

So when the plugin is loaded the mentioned error occurs and I am not able to move the cursor, edit any text or even close files using the keyboard (other commands such as switching between tabs still work using the keyboard).

I run Windows 10 Home version 10.0.18363 build 18363 and Neovim v0.5.0-566-g5f0a1b04c
After installing ActualVim using Package control I have set the neovim path in both settings files:
...\Sublime Text 3\Packages\User\ActualVim.sublime-settings
...\Sublime Text 3\Packages\ActualVim\settings.py

to ```"neovim_path": "C:\\Program Files\\Neovim\\bin"```. I also tried to set both to ```"neovim_path": "C:\\Program Files\\Neovim\\bin\\"``` and as a longshot I set it to ```"neovim_path": "C:\\Program Files\\Neovim\\bin\\nvim.exe"

**Console output:**
```
ActualVim: using nvim binary path: C:\Program Files\Neovim\bin\nvim.exe
ActualVim: Error during nvim setup.
Traceback (most recent call last):
  File "C:\Users\alwin\AppData\Roaming\Sublime Text 3\Packages\ActualVim\neo.py", line 79, in plugin_loaded
    vim._setup()
  File "C:\Users\alwin\AppData\Roaming\Sublime Text 3\Packages\ActualVim\neo.py", line 126, in _setup
    self.nv = neovim.attach('child', argv=[NEOVIM_PATH, '--embed', '-n'] + args)
  File "C:\Users\alwin\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\__init__.py", line 109, in attach
    return Nvim.from_session(session).with_decode(decode)
  File "C:\Users\alwin\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\api\nvim.py", line 51, in from_session
    channel_id, metadata = session.request(b'vim_get_api_info')
  File "C:\Users\alwin\AppData\Roaming\Sublime Text 3\Packages\ActualVim\lib\neovim\msgpack_rpc\session.py", line 109, in request
    raise IOError('EOF')
OSError: EOF
```

Thanks in advance for having a look at this error.

**Comment by lunixbochs** [comment]
I believe the path should not include bin\ or the exe. Just stop at neovim\
