### ISSUE TITLE
No autocompletion

### ISSUE THREAD

**Issue by xelra** [lunixbochs/actualvim#57]
When Actual Vim is active, the autocompletion of Sublime doesn't work.

**Comment by lunixbochs** [comment]
it should, but tab is intercepted by vim. you'll need a new hotkey, or we need a "sublime mode"

**Comment by xelra** [comment]
It doesn't show the autocompletion box. No completion at all.

I'm trying a simple html file. As soon as I disable ActualVim, the autocompletion box shows up.

Ideally the navigation of the box should be with `C-n` and `C-p`.

**Comment by lunixbochs** [comment]
You can press ctrl+space to show completions. I could press it automatically after every keystroke in insert mode.

**Comment by jordwalke** [comment]
How do you enable Vim's autocompletion? NeoVim exposes this.

**Comment by lunixbochs** [comment]
I can't easily show Vim UI like popovers yet (waiting for neovim remote UI improvements), but any vim commands should work if you press the input for them. Remember the neovim stores vimrc in a different place: https://github.com/neovim/neovim/wiki/FAQ#where-should-i-put-my-config-vimrc

**Comment by lunixbochs** [comment]
I was wrong about vim's autocompletion, popover menus should be available soon, track #74

**Comment by lunixbochs** [comment]
vim's autocompletion is available now:

![popupmenu_external](https://cloud.githubusercontent.com/assets/117642/23907367/42503040-08a7-11e7-9f2c-796f91526927.png)

How important is it for you to have Sublime's autocompletion?

**Comment by xelra** [comment]
One of the reasons I tried ActualVim in the first place was because although Neovim works well on Windows now, a lot of plugins don't. I was hoping to use the IDE-like features for golang from Sublime and combine them with Neovim.

**Comment by lunixbochs** [comment]
How does that translate to autocompletion specifically? I'm pretty sure I can feed sublime's autocompletion suggestions into vim if that would be sufficient. Are any other major IDE-like features broken?

**Comment by lunixbochs** [comment]
513fbdcdeaecf9a222d6928234ba12d4144d2ca2 now sets up a `completefunc` which uses Sublime's autocomplete (word completions and plugin completions, but not `.sublime-completion` files). This means any plugins handling autocomplete should work, and it integrates with my popupmenu stuff.

The default way to trigger `completefunc` is <kbd>^X</kbd><kbd>^U</kbd>. I think you can do the rest on Vim's side. Anything more I can do here?

**Comment by sarahlim** [comment]
Pardon my ignorance, but would it be possible to emulate the behavior of YouCompleteMe in ActualVim? I'm having trouble getting autocomplete suggestions to appear at all.

Great plugin, thank you!!

**Comment by lunixbochs** [comment]
Anything that uses basic vim popup menus should work. Wildmenu won't work until neovim has support for more external UI. I don't know what YouCompleteMe uses.

**Comment by lunixbochs** [comment]
I think this can be solved, to the point of restoring Sublime's original preview behavior, by #97

**Comment by marciol** [comment]
One thing that I really love on Sublime default autocompletion is the fuzzy search autocompletion, something that I have not found in default vim autocompletion plugins.

**Comment by cdt3pm** [comment]
I am getting an error with this. `^X` `^U` throws the following error
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 812, in run_
    return self.run(edit, **args)
  File "/Users/cdt3pm/Library/Application Support/Sublime Text 3/Packages/ActualVim/actual.py", line 63, in run
    v.press(key, edit=edit)
  File "/Users/cdt3pm/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 535, in press
    _, ready = neo.vim.press(key, onready)
  File "/Users/cdt3pm/Library/Application Support/Sublime Text 3/Packages/ActualVim/neo.py", line 299, in press
    res = self.nv.request('nvim_get_mode') or {}
  File "/Users/cdt3pm/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/nvim.py", line 134, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/cdt3pm/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 101, in request
    v = self._yielding_request(method, args, timeout=kwargs.pop('timeout', 0.25))
  File "/Users/cdt3pm/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/msgpack_rpc/session.py", line 162, in _yielding_request
    return q.get(timeout=timeout)
  File "./python3.3/queue.py", line 175, in get
queue.Empty
error caught in request handler 'complete ['1', '']'
Traceback (most recent call last):

  File "/Users/cdt3pm/Library/Application Support/Sublime Text 3/Packages/ActualVim/neo.py", line 229, in on_request
    return av.on_complete(args[0], args[1])

  File "/Users/cdt3pm/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 681, in on_complete
    word = self.view.word(cur())

  File "/Users/cdt3pm/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 676, in cur
    modified, et, ts, a, b = neo.vim.status()

ValueError: too many values to unpack (expected 5)
```

Did I do something to break this? Is there a setting which I can change to get the autocomplete to work? For the record, `ctrl+space` shows me the list of autocomplete options, but I cannot select them; Vim appears to handle enter and tab directly.

**Comment by lunixbochs** [comment]
That's a regression on my end, I'll fix it.

**Comment by lunixbochs** [comment]
Should be fixed in latest master and is released in 0.9.16

**Comment by li1** [comment]
Hi @lunixbochs ,

first of all, thanks for your great work on bringing vim to sublime!

I was wondering what the up-to-date status of this issue is (and perhaps related to that #97?).

Is there currently a way to trigger sublime's and/or vim's autocomplete automatically while typing in insert mode (i.e. without having to press a specific key)?

If not, what has to be done to achieve that? Which issue should I follow for updates on this?

Cheers, Malte

**Comment by lunixbochs** [comment]
I think vim-side completion like youcompleteme will work once I add external wildmenu support, which should be a very easy extension of the existing external menu but ActualVim is lower priority for me right now

**Comment by li1** [comment]
OK, cool, thanks for the update!

**Comment by hakunin** [comment]
I use Sublime sometimes and my plugins were just not compatible so I did this:
```
" skip if using ActualVim plugin for sublime-text
if !exists("g:actualvim")
  set runtimepath^=~/.vim runtimepath+=~/.vim/after
  let &packpath = &runtimepath
  source ~/.vimrc
endif

" define a different ~/.vimrc, or just a few utilities I want to use
if exists("g:actualvim")
end
```
And now I can start moving them one by one and see which break
