### ISSUE TITLE
ImportError: No module named 'actualvim' (Mac OSX)

### ISSUE THREAD

**Issue by pierodancona** [lunixbochs/actualvim#71]
Installed via Package Control, on Mac OSX 10.11.6. When I restart ST3 I get
an ImportError: No module named 'actualvim'.
Since I get another ImportError from RegReplace (no yaml)
this might be an issue with my installation rather than 
ActualVim, but how to fix it?

Here is the complete log (repeated three times):

reloading plugin ActualVim.actual
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/piero/Library/Application Support/Sublime Text 3/Packages/ActualVim/actual.py", line 6, in <module>
    from .view import ActualVim, enabled
  File "/Users/piero/Library/Application Support/Sublime Text 3/Packages/ActualVim/view.py", line 5, in <module>
    from . import neo
  File "/Users/piero/Library/Application Support/Sublime Text 3/Packages/ActualVim/neo.py", line 9, in <module>
    from .lib import neovim
  File "/Users/piero/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/__init__.py", line 9, in <module>
    from .api import Nvim
  File "/Users/piero/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/__init__.py", line 7, in <module>
    from .buffer import Buffer
  File "/Users/piero/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/buffer.py", line 2, in <module>
    from .common import Remote
  File "/Users/piero/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/common.py", line 4, in <module>
    from actualvim.lib.msgpack import unpackb
ImportError: No module named 'actualvim'
reloading plugin ActualVim.edit
reloading plugin ActualVim.neo
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/piero/Library/Application Support/Sublime Text 3/Packages/ActualVim/neo.py", line 9, in <module>
    from .lib import neovim
  File "/Users/piero/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/__init__.py", line 9, in <module>
    from .api import Nvim
  File "/Users/piero/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/__init__.py", line 7, in <module>
    from .buffer import Buffer
  File "/Users/piero/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/buffer.py", line 2, in <module>
    from .common import Remote
  File "/Users/piero/Library/Application Support/Sublime Text 3/Packages/ActualVim/lib/neovim/api/common.py", line 4, in <module>
    from actualvim.lib.msgpack import unpackb
ImportError: No module named 'actualvim'

**Comment by lunixbochs** [comment]
Oops, package control uses the package name rather than the repository name, and capitalization is different. Try the latest master: b00bc512cb0bf568a6820bd5ec963d358a3e6a28

**Comment by lunixbochs** [comment]
This should be fixed, can you confirm?

**Comment by pierodancona** [comment]
Yes it works now! thanks
