### ISSUE TITLE
[error] failed to save undo information

### ISSUE THREAD

**Issue by lunixbochs** [lunixbochs/actualvim#82]
This happened after Sublime reloaded a file. The underlying vim buffer was broken afterwards.

Can be repro'd by repeatedly running `touch` on the active view and clicking back into Sublime.

```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 389, in run_callback
    expr()
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 410, in <lambda>
    run_callback(name, vel, lambda: vel.__class__.__dict__[name](vel))
  File "/Library/Application Support/Sublime Text 3/Packages/actualvim/actual.py", line 80, in on_modified 
    self.v.sync_to_vim()
  File "/Library/Application Support/Sublime Text 3/Packages/actualvim/view.py", line 315, in sync_to_vim 
    self.buf[:] = text
  File "/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/api/buffer.py", line 73, in __setitem__ 
    return self._set_lines(start, end, False, lines)
  File "/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/api/buffer.py", line 39, in _set_lines
    return self.request_raw('nvim_buf_set_lines', start, end, strict, lines)
  File "/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/api/common.py", line 47, in request_raw 
    return self._session.request_raw(name, self._session._to_nvim(self), *args, **kwargs)
  File "/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/api/nvim.py", line 110, in request_raw 
    return self._session.request(name, *args, **kwargs)
  File "/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/msgpack_rpc/session.py", line 110, in request
    raise self.error_wrapper(err)
actualvim.lib.neovim.api.nvim.NvimError: b'Failed to save undo information'
```

**Comment by lunixbochs** [comment]
Looks like this only happens to ActualVim's view.py.

**Comment by mjedmonds** [comment]
Was there a fix for this? Experiencing the same issue.

**Comment by lunixbochs** [comment]
Please describe the exact issue you are experiencing, and reproduction steps. It might not be the same.
