### ISSUE TITLE
No Module named ActualVim

### ISSUE THREAD

**Issue by bs** [lunixbochs/ActualVim#90]
One thing I found odd was that there was no default config to set the path, just a blank file, so I hedged on putting in:

`{    
    "enabled": true,
    "neovim_path": "/opt/local/bin/nvim"
}`

Perhaps that is not correct?

Full dump of log here.

reloading plugin actualvim.actual
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/actual.py", line 6, in <module>
    from .view import ActualVim
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/view.py", line 7, in <module>
    from . import neo
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/neo.py", line 10, in <module>
    from .lib import neovim
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/__init__.py", line 8, in <module>
    from .api import Nvim
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/api/__init__.py", line 7, in <module>
    from .buffer import Buffer
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/api/buffer.py", line 2, in <module>
    from .common import Remote
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/api/common.py", line 4, in <module>
    from ActualVim.lib import msgpack
ImportError: No module named 'ActualVim'
reloading plugin actualvim.edit
reloading plugin actualvim.neo
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/neo.py", line 10, in <module>
    from .lib import neovim
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/__init__.py", line 8, in <module>
    from .api import Nvim
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/api/__init__.py", line 7, in <module>
    from .buffer import Buffer
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/api/buffer.py", line 2, in <module>
    from .common import Remote
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/api/common.py", line 4, in <module>
    from ActualVim.lib import msgpack
ImportError: No module named 'ActualVim'
reloading plugin actualvim.screen
reloading plugin actualvim.settings
reloading plugin actualvim.view
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/view.py", line 7, in <module>
    from . import neo
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/neo.py", line 10, in <module>
    from .lib import neovim
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/__init__.py", line 8, in <module>
    from .api import Nvim
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/api/__init__.py", line 7, in <module>
    from .buffer import Buffer
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/api/buffer.py", line 2, in <module>
    from .common import Remote
  File "/Users/britt/Library/Application Support/Sublime Text 3/Packages/actualvim/lib/neovim/api/common.py", line 4, in <module>
    from ActualVim.lib import msgpack
ImportError: No module named 'ActualVim'
plugins loaded

**Comment by lunixbochs** [comment]
Due to Package Control overriding the repository name, I've renamed the import path from "actualvim" in lowercase to the capitalized "ActualVim" and renamed the project respectively. You should rename your folder.

This was a few weeks ago. Have you somehow installed a lowercase version since then?

If the ActualVim plugin is working properly, opening the settings file via the menu or command palette will merge your user settings with the defaults.

**Comment by bs** [comment]
Yeah, I saw that, and I thought for sure I had cloned the correct one. Looking back through my buffer history, though, I found:

git clone https://github.com/lunixbochs/actualvim

No idea how I got the lowercae url, but that of course put it in the wrong folder.
