### ISSUE TITLE
ImportError: No module named 'ActualVim'

### ISSUE THREAD

**Issue by markonius** [lunixbochs/ActualVim#98]
Hi. I get the following error on startup.

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\redacted\AppData\Roaming\Sublime Text 3\Packages\ActualVim-master\actual.py", line 6, in <module>
    from .view import ActualVim
  File "C:\Users\redacted\AppData\Roaming\Sublime Text 3\Packages\ActualVim-master\view.py", line 7, in <module>
    from . import neo
  File "C:\Users\redacted\AppData\Roaming\Sublime Text 3\Packages\ActualVim-master\neo.py", line 10, in <module>
    from .lib import neovim
  File "C:\Users\redacted\AppData\Roaming\Sublime Text 3\Packages\ActualVim-master\lib\neovim\__init__.py", line 8, in <module>
    from .api import Nvim
  File "C:\Users\redacted\AppData\Roaming\Sublime Text 3\Packages\ActualVim-master\lib\neovim\api\__init__.py", line 7, in <module>
    from .buffer import Buffer
  File "C:\Users\redacted\AppData\Roaming\Sublime Text 3\Packages\ActualVim-master\lib\neovim\api\buffer.py", line 2, in <module>
    from .common import Remote
  File "C:\Users\redacted\AppData\Roaming\Sublime Text 3\Packages\ActualVim-master\lib\neovim\api\common.py", line 4, in <module>
    from ActualVim.lib import msgpack
ImportError: No module named 'ActualVim'
```

**Comment by lunixbochs** [comment]
You unzipped to `ActualVim-master`. You need to rename the package to ActualVim. It can't import its dependencies.

**Comment by markonius** [comment]
Thanks! It works! This is the best thing ever :D
